# Generated by Django 5.2.1 on 2025-05-23 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriveAxleModel',
            fields=[
                ('reference_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.reference')),
            ],
            bases=('core.reference',),
        ),
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('reference_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.reference')),
            ],
            bases=('core.reference',),
        ),
        migrations.CreateModel(
            name='FailureNode',
            fields=[
                ('reference_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.reference')),
            ],
            bases=('core.reference',),
        ),
        migrations.CreateModel(
            name='ModelType',
            fields=[
                ('reference_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.reference')),
            ],
            bases=('core.reference',),
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('reference_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.reference')),
            ],
            bases=('core.reference',),
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('reference_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.reference')),
            ],
            bases=('core.reference',),
        ),
        migrations.CreateModel(
            name='SteeredAxleModel',
            fields=[
                ('reference_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.reference')),
            ],
            bases=('core.reference',),
        ),
        migrations.CreateModel(
            name='TOType',
            fields=[
                ('reference_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.reference')),
            ],
            bases=('core.reference',),
        ),
        migrations.CreateModel(
            name='TransmissionModel',
            fields=[
                ('reference_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.reference')),
            ],
            bases=('core.reference',),
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('engine_serial', models.CharField(max_length=100)),
                ('transmission_serial', models.CharField(max_length=100)),
                ('drive_axle_serial', models.CharField(max_length=100)),
                ('steered_axle_serial', models.CharField(max_length=100)),
                ('supply_contract', models.CharField(max_length=255)),
                ('shipment_date', models.DateField()),
                ('customer', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('additional_equipment', models.TextField(blank=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_as_client', to=settings.AUTH_USER_MODEL)),
                ('service_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_as_service', to=settings.AUTH_USER_MODEL)),
                ('drive_axle_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.driveaxlemodel')),
                ('engine_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.enginemodel')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modeltype')),
                ('steered_axle_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.steeredaxlemodel')),
                ('transmission_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transmissionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('operating_hours', models.IntegerField()),
                ('description', models.TextField()),
                ('parts_used', models.TextField()),
                ('recovery_date', models.DateField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.machine')),
                ('failure_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.failurenode')),
                ('recovery_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.recoverymethod')),
                ('service_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servicecompany')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('operating_hours', models.IntegerField()),
                ('order_number', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.machine')),
                ('service_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servicecompany')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.totype')),
            ],
        ),
    ]
